services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.ci
      target: builder
    working_dir: /app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops_default
    command: sh -c "timeout 900 gradle :test :jacocoTestReport --no-daemon -Dspring.profiles.active=test"

networks:
  devops_default:
    external: true
